# Generated by Django 5.0.3 on 2024-03-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
